// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/OrangePortraitEventPoster-VddDAF/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-VddDAF/DeepOrangePoster.tsx"),
  "./components/mockups/templates/SeveranceDinnerPartyInvite-M76x2Z/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-M76x2Z/DinnerPartyPosterSeverance.tsx"),
  "./components/mockups/templates/SeveranceDinnerPartyInvite-kjMmbO/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-kjMmbO/DinnerPartyPosterSeverance.tsx")
};
